version: "3.8"

name: ees_report_app

services:
  express-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:pass@db:5432/mydatabase"
    command: >
      sh -c "sleep 5 &&
         npx prisma db push &&
         npm start"
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  react-app:
    build: ../react-client
    ports:
      - "80:80"

volumes:
  db_data:
